changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Model Catalog
      labels:
        - catalog
    - title: Other Changes
      labels:
        - "*"
